# Generated by Django 4.2 on 2024-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecognizedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_json_response', models.JSONField()),
                ('recyclable_items', models.TextField(help_text='Comma seprated Items')),
                ('non_recyclable_items', models.TextField(help_text='Comma seprated Items')),
                ('images', models.ManyToManyField(related_name='recognized_items', to='gemini_ai.imageuploaded')),
            ],
        ),
    ]
