# Generated by Django 4.2 on 2024-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizeditem',
            name='non_recyclable_items',
            field=models.TextField(blank=True, help_text='Comma seprated Items', null=True),
        ),
        migrations.AlterField(
            model_name='recognizeditem',
            name='recyclable_items',
            field=models.TextField(blank=True, help_text='Comma seprated Items', null=True),
        ),
    ]
